#!/usr/bin/env python

import tkinter

from modules import compiler
from modules import comgui
from modules import arguments

args = arguments.parse()

# Trigger the actual program....
if args.gui:
    window = tkinter.Tk()
    comgui = comgui.MainWindow(window)
    window.mainloop()
else:
    compiler.run(args)
